// This class is a part of the fork from neosmarts unicode.net (https://github.com/neosmart/unicode.net)
// Source: https://github.com/UWPX/unicode.net
// Original license:
// MIT License:
// https://github.com/UWPX/unicode.net/blob/master/LICENSE

using System.Collections.Generic;

namespace NeoSmart.Unicode
{
    // This file is machine-generated based on the official Unicode Consortium publication (https://unicode.org/Public/emoji/12.0/emoji-test.txt).
    // See https://github.com/UWPX/Emoji-List-Parser for the generator.
    public static partial class Emoji
    {
        /// <summary>
        /// A (sorted) enumeration of all emoji in group: TRAVEL_AND_PLACES
        /// Only contains fully-qualified and component emoji.
        /// <summary>
#if NET20 || NET30 || NET35
        public static readonly List<SingleEmoji> TravelAndPlaces = new List<SingleEmoji>() {
#else
        public static SortedSet<SingleEmoji> TravelAndPlaces => new SortedSet<SingleEmoji>() {
#endif
            /* 🌍 */ GlobeShowingEuropeAfrica,
            /* 🌎 */ GlobeShowingAmericas,
            /* 🌏 */ GlobeShowingAsiaAustralia,
            /* 🌐 */ GlobeMeridians,
            /* 🗺️ */ WorldMap,
            /* 🗾 */ MapJapan,
            /* 🧭 */ Compass,
            /* 🏔️ */ SnowCappedMountain,
            /* ⛰️ */ Mountain,
            /* 🌋 */ Volcano,
            /* 🗻 */ MountFuji,
            /* 🏕️ */ Camping,
            /* 🏖️ */ BeachUmbrella,
            /* 🏜️ */ Desert,
            /* 🏝️ */ DesertIsland,
            /* 🏞️ */ NationalPark,
            /* 🏟️ */ Stadium,
            /* 🏛️ */ ClassicalBuilding,
            /* 🏗️ */ BuildingConstruction,
            /* 🧱 */ Brick,
            /* 🏘️ */ Houses,
            /* 🏚️ */ DerelictHouse,
            /* 🏠 */ House,
            /* 🏡 */ HouseGarden,
            /* 🏢 */ OfficeBuilding,
            /* 🏣 */ JapanesePostOffice,
            /* 🏤 */ PostOffice,
            /* 🏥 */ Hospital,
            /* 🏦 */ Bank,
            /* 🏨 */ Hotel,
            /* 🏩 */ LoveHotel,
            /* 🏪 */ ConvenienceStore,
            /* 🏫 */ School,
            /* 🏬 */ DepartmentStore,
            /* 🏭 */ Factory,
            /* 🏯 */ JapaneseCastle,
            /* 🏰 */ Castle,
            /* 💒 */ Wedding,
            /* 🗼 */ TokyoTower,
            /* 🗽 */ StatueLiberty,
            /* ⛪ */ Church,
            /* 🕌 */ Mosque,
            /* 🛕 */ HinduTemple,
            /* 🕍 */ Synagogue,
            /* ⛩️ */ ShintoShrine,
            /* 🕋 */ Kaaba,
            /* ⛲ */ Fountain,
            /* ⛺ */ Tent,
            /* 🌁 */ Foggy,
            /* 🌃 */ NightStars,
            /* 🏙️ */ Cityscape,
            /* 🌄 */ SunriseOverMountains,
            /* 🌅 */ Sunrise,
            /* 🌆 */ CityscapeAtDusk,
            /* 🌇 */ Sunset,
            /* 🌉 */ BridgeAtNight,
            /* ♨️ */ HotSprings,
            /* 🎠 */ CarouselHorse,
            /* 🎡 */ FerrisWheel,
            /* 🎢 */ RollerCoaster,
            /* 💈 */ BarberPole,
            /* 🎪 */ CircusTent,
            /* 🚂 */ Locomotive,
            /* 🚃 */ RailwayCar,
            /* 🚄 */ HighSpeedTrain,
            /* 🚅 */ BulletTrain,
            /* 🚆 */ Train,
            /* 🚇 */ Metro,
            /* 🚈 */ LightRail,
            /* 🚉 */ Station,
            /* 🚊 */ Tram,
            /* 🚝 */ Monorail,
            /* 🚞 */ MountainRailway,
            /* 🚋 */ TramCar,
            /* 🚌 */ Bus,
            /* 🚍 */ OncomingBus,
            /* 🚎 */ Trolleybus,
            /* 🚐 */ Minibus,
            /* 🚑 */ Ambulance,
            /* 🚒 */ FireEngine,
            /* 🚓 */ PoliceCar,
            /* 🚔 */ OncomingPoliceCar,
            /* 🚕 */ Taxi,
            /* 🚖 */ OncomingTaxi,
            /* 🚗 */ Automobile,
            /* 🚘 */ OncomingAutomobile,
            /* 🚙 */ SportUtilityVehicle,
            /* 🚚 */ DeliveryTruck,
            /* 🚛 */ ArticulatedLorry,
            /* 🚜 */ Tractor,
            /* 🏎️ */ RacingCar,
            /* 🏍️ */ Motorcycle,
            /* 🛵 */ MotorScooter,
            /* 🦽 */ ManualWheelchair,
            /* 🦼 */ MotorizedWheelchair,
            /* 🛺 */ AutoRickshaw,
            /* 🚲 */ Bicycle,
            /* 🛴 */ KickScooter,
            /* 🛹 */ Skateboard,
            /* 🚏 */ BusStop,
            /* 🛣️ */ Motorway,
            /* 🛤️ */ RailwayTrack,
            /* 🛢️ */ OilDrum,
            /* ⛽ */ FuelPump,
            /* 🚨 */ PoliceCarLight,
            /* 🚥 */ HorizontalTrafficLight,
            /* 🚦 */ VerticalTrafficLight,
            /* 🛑 */ StopSign,
            /* 🚧 */ Construction,
            /* ⚓ */ Anchor,
            /* ⛵ */ Sailboat,
            /* 🛶 */ Canoe,
            /* 🚤 */ Speedboat,
            /* 🛳️ */ PassengerShip,
            /* ⛴️ */ Ferry,
            /* 🛥️ */ MotorBoat,
            /* 🚢 */ Ship,
            /* ✈️ */ Airplane,
            /* 🛩️ */ SmallAirplane,
            /* 🛫 */ AirplaneDeparture,
            /* 🛬 */ AirplaneArrival,
            /* 🪂 */ Parachute,
            /* 💺 */ Seat,
            /* 🚁 */ Helicopter,
            /* 🚟 */ SuspensionRailway,
            /* 🚠 */ MountainCableway,
            /* 🚡 */ AerialTramway,
            /* 🛰️ */ Satellite,
            /* 🚀 */ Rocket,
            /* 🛸 */ FlyingSaucer,
            /* 🛎️ */ BellhopBell,
            /* 🧳 */ Luggage,
            /* ⌛ */ HourglassDone,
            /* ⏳ */ HourglassNotDone,
            /* ⌚ */ Watch,
            /* ⏰ */ AlarmClock,
            /* ⏱️ */ Stopwatch,
            /* ⏲️ */ TimerClock,
            /* 🕰️ */ MantelpieceClock,
            /* 🕛 */ TwelveOclock,
            /* 🕧 */ TwelveThirty,
            /* 🕐 */ OneOclock,
            /* 🕜 */ OneThirty,
            /* 🕑 */ TwoOclock,
            /* 🕝 */ TwoThirty,
            /* 🕒 */ ThreeOclock,
            /* 🕞 */ ThreeThirty,
            /* 🕓 */ FourOclock,
            /* 🕟 */ FourThirty,
            /* 🕔 */ FiveOclock,
            /* 🕠 */ FiveThirty,
            /* 🕕 */ SixOclock,
            /* 🕡 */ SixThirty,
            /* 🕖 */ SevenOclock,
            /* 🕢 */ SevenThirty,
            /* 🕗 */ EightOclock,
            /* 🕣 */ EightThirty,
            /* 🕘 */ NineOclock,
            /* 🕤 */ NineThirty,
            /* 🕙 */ TenOclock,
            /* 🕥 */ TenThirty,
            /* 🕚 */ ElevenOclock,
            /* 🕦 */ ElevenThirty,
            /* 🌑 */ NewMoon,
            /* 🌒 */ WaxingCrescentMoon,
            /* 🌓 */ FirstQuarterMoon,
            /* 🌔 */ WaxingGibbousMoon,
            /* 🌕 */ FullMoon,
            /* 🌖 */ WaningGibbousMoon,
            /* 🌗 */ LastQuarterMoon,
            /* 🌘 */ WaningCrescentMoon,
            /* 🌙 */ CrescentMoon,
            /* 🌚 */ NewMoonFace,
            /* 🌛 */ FirstQuarterMoonFace,
            /* 🌜 */ LastQuarterMoonFace,
            /* 🌡️ */ Thermometer,
            /* ☀️ */ Sun,
            /* 🌝 */ FullMoonFace,
            /* 🌞 */ SunFace,
            /* 🪐 */ RingedPlanet,
            /* ⭐ */ Star,
            /* 🌟 */ GlowingStar,
            /* 🌠 */ ShootingStar,
            /* 🌌 */ MilkyWay,
            /* ☁️ */ Cloud,
            /* ⛅ */ SunBehindCloud,
            /* ⛈️ */ CloudLightningRain,
            /* 🌤️ */ SunBehindSmallCloud,
            /* 🌥️ */ SunBehindLargeCloud,
            /* 🌦️ */ SunBehindRainCloud,
            /* 🌧️ */ CloudRain,
            /* 🌨️ */ CloudSnow,
            /* 🌩️ */ CloudLightning,
            /* 🌪️ */ Tornado,
            /* 🌫️ */ Fog,
            /* 🌬️ */ WindFace,
            /* 🌀 */ Cyclone,
            /* 🌈 */ Rainbow,
            /* 🌂 */ ClosedUmbrella,
            /* ☂️ */ Umbrella,
            /* ☔ */ UmbrellaRainDrops,
            /* ⛱️ */ UmbrellaGround,
            /* ⚡ */ HighVoltage,
            /* ❄️ */ Snowflake,
            /* ☃️ */ Snowman,
            /* ⛄ */ SnowmanSnow,
            /* ☄️ */ Comet,
            /* 🔥 */ Fire,
            /* 💧 */ Droplet,
            /* 🌊 */ WaterWave,
        };
    }
}
