using System.Collections.Generic;

namespace NeoSmart.Unicode
{
    // This file is machine-generated based on the official Unicode Consortium publication (https://unicode.org/Public/emoji/14.0/emoji-test.txt).
    // See https://github.com/UWPX/Emoji-List-Parser for the generator.
    public static partial class Emoji
    {
        /// <summary>
        /// A (sorted) enumeration of all emoji in group: FOOD_AND_DRINK
        /// Only contains fully-qualified and component emoji.
        /// <summary>
#if NET20 || NET30 || NET35
        public static readonly List<SingleEmoji> FoodAndDrink = new List<SingleEmoji>() {
#else
        public static SortedSet<SingleEmoji> FoodAndDrink => new SortedSet<SingleEmoji>() {
#endif
            /* 🍇 */ Grapes_E0_6,
            /* 🍈 */ Melon_E0_6,
            /* 🍉 */ Watermelon_E0_6,
            /* 🍊 */ Tangerine_E0_6,
            /* 🍋 */ Lemon_E1_0,
            /* 🍌 */ Banana_E0_6,
            /* 🍍 */ Pineapple_E0_6,
            /* 🥭 */ Mango_E11_0,
            /* 🍎 */ RedApple_E0_6,
            /* 🍏 */ GreenApple_E0_6,
            /* 🍐 */ Pear_E1_0,
            /* 🍑 */ Peach_E0_6,
            /* 🍒 */ Cherries_E0_6,
            /* 🍓 */ Strawberry_E0_6,
            /* 🫐 */ Blueberries_E13_0,
            /* 🥝 */ KiwiFruit_E3_0,
            /* 🍅 */ Tomato_E0_6,
            /* 🫒 */ Olive_E13_0,
            /* 🥥 */ Coconut_E5_0,
            /* 🥑 */ Avocado_E3_0,
            /* 🍆 */ Eggplant_E0_6,
            /* 🥔 */ Potato_E3_0,
            /* 🥕 */ Carrot_E3_0,
            /* 🌽 */ EarCorn_E0_6,
            /* 🌶️ */ HotPepper_E0_7,
            /* 🫑 */ BellPepper_E13_0,
            /* 🥒 */ Cucumber_E3_0,
            /* 🥬 */ LeafyGreen_E11_0,
            /* 🥦 */ Broccoli_E5_0,
            /* 🧄 */ Garlic_E12_0,
            /* 🧅 */ Onion_E12_0,
            /* 🍄 */ Mushroom_E0_6,
            /* 🥜 */ Peanuts_E3_0,
            /* 🫘 */ Beans_E14_0,
            /* 🌰 */ Chestnut_E0_6,
            /* 🍞 */ Bread_E0_6,
            /* 🥐 */ Croissant_E3_0,
            /* 🥖 */ BaguetteBread_E3_0,
            /* 🫓 */ Flatbread_E13_0,
            /* 🥨 */ Pretzel_E5_0,
            /* 🥯 */ Bagel_E11_0,
            /* 🥞 */ Pancakes_E3_0,
            /* 🧇 */ Waffle_E12_0,
            /* 🧀 */ CheeseWedge_E1_0,
            /* 🍖 */ MeatBone_E0_6,
            /* 🍗 */ PoultryLeg_E0_6,
            /* 🥩 */ CutMeat_E5_0,
            /* 🥓 */ Bacon_E3_0,
            /* 🍔 */ Hamburger_E0_6,
            /* 🍟 */ FrenchFries_E0_6,
            /* 🍕 */ Pizza_E0_6,
            /* 🌭 */ HotDog_E1_0,
            /* 🥪 */ Sandwich_E5_0,
            /* 🌮 */ Taco_E1_0,
            /* 🌯 */ Burrito_E1_0,
            /* 🫔 */ Tamale_E13_0,
            /* 🥙 */ StuffedFlatbread_E3_0,
            /* 🧆 */ Falafel_E12_0,
            /* 🥚 */ Egg_E3_0,
            /* 🍳 */ Cooking_E0_6,
            /* 🥘 */ ShallowPanFood_E3_0,
            /* 🍲 */ PotFood_E0_6,
            /* 🫕 */ Fondue_E13_0,
            /* 🥣 */ BowlSpoon_E5_0,
            /* 🥗 */ GreenSalad_E3_0,
            /* 🍿 */ Popcorn_E1_0,
            /* 🧈 */ Butter_E12_0,
            /* 🧂 */ Salt_E11_0,
            /* 🥫 */ CannedFood_E5_0,
            /* 🍱 */ BentoBox_E0_6,
            /* 🍘 */ RiceCracker_E0_6,
            /* 🍙 */ RiceBall_E0_6,
            /* 🍚 */ CookedRice_E0_6,
            /* 🍛 */ CurryRice_E0_6,
            /* 🍜 */ SteamingBowl_E0_6,
            /* 🍝 */ Spaghetti_E0_6,
            /* 🍠 */ RoastedSweetPotato_E0_6,
            /* 🍢 */ Oden_E0_6,
            /* 🍣 */ Sushi_E0_6,
            /* 🍤 */ FriedShrimp_E0_6,
            /* 🍥 */ FishCakeSwirl_E0_6,
            /* 🥮 */ MoonCake_E11_0,
            /* 🍡 */ Dango_E0_6,
            /* 🥟 */ Dumpling_E5_0,
            /* 🥠 */ FortuneCookie_E5_0,
            /* 🥡 */ TakeoutBox_E5_0,
            /* 🦀 */ Crab_E1_0,
            /* 🦞 */ Lobster_E11_0,
            /* 🦐 */ Shrimp_E3_0,
            /* 🦑 */ Squid_E3_0,
            /* 🦪 */ Oyster_E12_0,
            /* 🍦 */ SoftIceCream_E0_6,
            /* 🍧 */ ShavedIce_E0_6,
            /* 🍨 */ IceCream_E0_6,
            /* 🍩 */ Doughnut_E0_6,
            /* 🍪 */ Cookie_E0_6,
            /* 🎂 */ BirthdayCake_E0_6,
            /* 🍰 */ Shortcake_E0_6,
            /* 🧁 */ Cupcake_E11_0,
            /* 🥧 */ Pie_E5_0,
            /* 🍫 */ ChocolateBar_E0_6,
            /* 🍬 */ Candy_E0_6,
            /* 🍭 */ Lollipop_E0_6,
            /* 🍮 */ Custard_E0_6,
            /* 🍯 */ HoneyPot_E0_6,
            /* 🍼 */ BabyBottle_E1_0,
            /* 🥛 */ GlassMilk_E3_0,
            /* ☕ */ HotBeverage_E0_6,
            /* 🫖 */ Teapot_E13_0,
            /* 🍵 */ TeacupHandle_E0_6,
            /* 🍶 */ Sake_E0_6,
            /* 🍾 */ BottlePoppingCork_E1_0,
            /* 🍷 */ WineGlass_E0_6,
            /* 🍸 */ CocktailGlass_E0_6,
            /* 🍹 */ TropicalDrink_E0_6,
            /* 🍺 */ BeerMug_E0_6,
            /* 🍻 */ ClinkingBeerMugs_E0_6,
            /* 🥂 */ ClinkingGlasses_E3_0,
            /* 🥃 */ TumblerGlass_E3_0,
            /* 🫗 */ PouringLiquid_E14_0,
            /* 🥤 */ CupStraw_E5_0,
            /* 🧋 */ BubbleTea_E13_0,
            /* 🧃 */ BeverageBox_E12_0,
            /* 🧉 */ Mate_E12_0,
            /* 🧊 */ Ice_E12_0,
            /* 🥢 */ Chopsticks_E5_0,
            /* 🍽️ */ ForkKnifePlate_E0_7,
            /* 🍴 */ ForkKnife_E0_6,
            /* 🥄 */ Spoon_E3_0,
            /* 🔪 */ KitchenKnife_E0_6,
            /* 🫙 */ Jar_E14_0,
            /* 🏺 */ Amphora_E1_0,
        };
    }
}
