// This class is a part of the fork from neosmarts unicode.net (https://github.com/neosmart/unicode.net)
// Source: https://github.com/UWPX/unicode.net
// Original license:
// MIT License:
// https://github.com/UWPX/unicode.net/blob/master/LICENSE

using System.Collections.Generic;

namespace NeoSmart.Unicode
{
    // This file is machine-generated based on the official Unicode Consortium publication (https://unicode.org/Public/emoji/12.0/emoji-test.txt).
    // See https://github.com/UWPX/Emoji-List-Parser for the generator.
    public static partial class Emoji
    {
        /// <summary>
        /// A (sorted) enumeration of all emoji in group: ANIMALS_AND_NATURE
        /// Only contains fully-qualified and component emoji.
        /// <summary>
#if NET20 || NET30 || NET35
        public static readonly List<SingleEmoji> AnimalsAndNature = new List<SingleEmoji>() {
#else
        public static SortedSet<SingleEmoji> AnimalsAndNature => new SortedSet<SingleEmoji>() {
#endif
            /* 🐱‍👤 */ NinjaCat,
            /* 🐱‍👓 */ HipsterCat,
            /* 🐱‍💻 */ HackerCat,
            /* 🐱‍🐉 */ DinoCat,
            /* 🐱‍🏍 */ StuntCat,
            /* 🐱‍🚀 */ AstroCat,
            /* 🐵 */ MonkeyFace,
            /* 🐒 */ Monkey,
            /* 🦍 */ Gorilla,
            /* 🦧 */ Orangutan,
            /* 🐶 */ DogFace,
            /* 🐕 */ Dog,
            /* 🦮 */ GuideDog,
            /* 🐕‍🦺 */ ServiceDog,
            /* 🐩 */ Poodle,
            /* 🐺 */ Wolf,
            /* 🦊 */ Fox,
            /* 🦝 */ Raccoon,
            /* 🐱 */ CatFace,
            /* 🐈 */ Cat,
            /* 🦁 */ Lion,
            /* 🐯 */ TigerFace,
            /* 🐅 */ Tiger,
            /* 🐆 */ Leopard,
            /* 🐴 */ HorseFace,
            /* 🐎 */ Horse,
            /* 🦄 */ Unicorn,
            /* 🦓 */ Zebra,
            /* 🦌 */ Deer,
            /* 🐮 */ CowFace,
            /* 🐂 */ Ox,
            /* 🐃 */ WaterBuffalo,
            /* 🐄 */ Cow,
            /* 🐷 */ PigFace,
            /* 🐖 */ Pig,
            /* 🐗 */ Boar,
            /* 🐽 */ PigNose,
            /* 🐏 */ Ram,
            /* 🐑 */ Ewe,
            /* 🐐 */ Goat,
            /* 🐪 */ Camel,
            /* 🐫 */ TwoHumpCamel,
            /* 🦙 */ Llama,
            /* 🦒 */ Giraffe,
            /* 🐘 */ Elephant,
            /* 🦏 */ Rhinoceros,
            /* 🦛 */ Hippopotamus,
            /* 🐭 */ MouseFace,
            /* 🐁 */ Mouse,
            /* 🐀 */ Rat,
            /* 🐹 */ Hamster,
            /* 🐰 */ RabbitFace,
            /* 🐇 */ Rabbit,
            /* 🐿️ */ Chipmunk,
            /* 🦔 */ Hedgehog,
            /* 🦇 */ Bat,
            /* 🐻 */ Bear,
            /* 🐨 */ Koala,
            /* 🐼 */ Panda,
            /* 🦥 */ Sloth,
            /* 🦦 */ Otter,
            /* 🦨 */ Skunk,
            /* 🦘 */ Kangaroo,
            /* 🦡 */ Badger,
            /* 🐾 */ PawPrints,
            /* 🦃 */ Turkey,
            /* 🐔 */ Chicken,
            /* 🐓 */ Rooster,
            /* 🐣 */ HatchingChick,
            /* 🐤 */ BabyChick,
            /* 🐥 */ FrontFacingBabyChick,
            /* 🐦 */ Bird,
            /* 🐧 */ Penguin,
            /* 🕊️ */ Dove,
            /* 🦅 */ Eagle,
            /* 🦆 */ Duck,
            /* 🦢 */ Swan,
            /* 🦉 */ Owl,
            /* 🦩 */ Flamingo,
            /* 🦚 */ Peacock,
            /* 🦜 */ Parrot,
            /* 🐸 */ Frog,
            /* 🐊 */ Crocodile,
            /* 🐢 */ Turtle,
            /* 🦎 */ Lizard,
            /* 🐍 */ Snake,
            /* 🐲 */ DragonFace,
            /* 🐉 */ Dragon,
            /* 🦕 */ Sauropod,
            /* 🦖 */ TRex,
            /* 🐳 */ SpoutingWhale,
            /* 🐋 */ Whale,
            /* 🐬 */ Dolphin,
            /* 🐟 */ Fish,
            /* 🐠 */ TropicalFish,
            /* 🐡 */ Blowfish,
            /* 🦈 */ Shark,
            /* 🐙 */ Octopus,
            /* 🐚 */ SpiralShell,
            /* 🐌 */ Snail,
            /* 🦋 */ Butterfly,
            /* 🐛 */ Bug,
            /* 🐜 */ Ant,
            /* 🐝 */ Honeybee,
            /* 🐞 */ LadyBeetle,
            /* 🦗 */ Cricket,
            /* 🕷️ */ Spider,
            /* 🕸️ */ SpiderWeb,
            /* 🦂 */ Scorpion,
            /* 🦟 */ Mosquito,
            /* 🦠 */ Microbe,
            /* 💐 */ Bouquet,
            /* 🌸 */ CherryBlossom,
            /* 💮 */ WhiteFlower,
            /* 🏵️ */ Rosette,
            /* 🌹 */ Rose,
            /* 🥀 */ WiltedFlower,
            /* 🌺 */ Hibiscus,
            /* 🌻 */ Sunflower,
            /* 🌼 */ Blossom,
            /* 🌷 */ Tulip,
            /* 🌱 */ Seedling,
            /* 🌲 */ EvergreenTree,
            /* 🌳 */ DeciduousTree,
            /* 🌴 */ PalmTree,
            /* 🌵 */ Cactus,
            /* 🌾 */ SheafRice,
            /* 🌿 */ Herb,
            /* ☘️ */ Shamrock,
            /* 🍀 */ FourLeafClover,
            /* 🍁 */ MapleLeaf,
            /* 🍂 */ FallenLeaf,
            /* 🍃 */ LeafFlutteringWind,
        };
    }
}
