using System.Collections.Generic;

namespace NeoSmart.Unicode
{
    // This file is machine-generated based on the official Unicode Consortium publication (https://unicode.org/Public/emoji/12.0/emoji-test.txt).
    // See https://github.com/UWPX/Emoji-List-Parser for the generator.
    public static partial class Emoji
    {
        /// <summary>
        /// A (sorted) enumeration of all emoji in group: SMILEYS_AND_EMOTION
        /// Only contains fully-qualified and component emoji.
        /// <summary>
#if NET20 || NET30 || NET35
        public static readonly List<SingleEmoji> SmileysAndEmotion = new List<SingleEmoji>() {
#else
        public static SortedSet<SingleEmoji> SmileysAndEmotion => new SortedSet<SingleEmoji>() {
#endif
            /* 😀 */ GrinningFace,
            /* 😃 */ GrinningFaceBigEyes,
            /* 😄 */ GrinningFaceSmilingEyes,
            /* 😁 */ BeamingFaceSmilingEyes,
            /* 😆 */ GrinningSquintingFace,
            /* 😅 */ GrinningFaceSweat,
            /* 🤣 */ RollingFloorLaughing,
            /* 😂 */ FaceTearsJoy,
            /* 🙂 */ SlightlySmilingFace,
            /* 🙃 */ UpsideDownFace,
            /* 😉 */ WinkingFace,
            /* 😊 */ SmilingFaceSmilingEyes,
            /* 😇 */ SmilingFaceHalo,
            /* 🥰 */ SmilingFaceHearts,
            /* 😍 */ SmilingFaceHeartEyes,
            /* 🤩 */ StarStruck,
            /* 😘 */ FaceBlowingAKiss,
            /* 😗 */ KissingFace,
            /* ☺️ */ SmilingFace,
            /* 😚 */ KissingFaceClosedEyes,
            /* 😙 */ KissingFaceSmilingEyes,
            /* 😋 */ FaceSavoringFood,
            /* 😛 */ FaceTongue,
            /* 😜 */ WinkingFaceTongue,
            /* 🤪 */ ZanyFace,
            /* 😝 */ SquintingFaceTongue,
            /* 🤑 */ MoneyMouthFace,
            /* 🤗 */ HuggingFace,
            /* 🤭 */ FaceHandOverMouth,
            /* 🤫 */ ShushingFace,
            /* 🤔 */ ThinkingFace,
            /* 🤐 */ ZipperMouthFace,
            /* 🤨 */ FaceRaisedEyebrow,
            /* 😐 */ NeutralFace,
            /* 😑 */ ExpressionlessFace,
            /* 😶 */ FaceMouth,
            /* 😏 */ SmirkingFace,
            /* 😒 */ UnamusedFace,
            /* 🙄 */ FaceRollingEyes,
            /* 😬 */ GrimacingFace,
            /* 🤥 */ LyingFace,
            /* 😌 */ RelievedFace,
            /* 😔 */ PensiveFace,
            /* 😪 */ SleepyFace,
            /* 🤤 */ DroolingFace,
            /* 😴 */ SleepingFace,
            /* 😷 */ FaceMedicalMask,
            /* 🤒 */ FaceThermometer,
            /* 🤕 */ FaceHeadBandage,
            /* 🤢 */ NauseatedFace,
            /* 🤮 */ FaceVomiting,
            /* 🤧 */ SneezingFace,
            /* 🥵 */ HotFace,
            /* 🥶 */ ColdFace,
            /* 🥴 */ WoozyFace,
            /* 😵 */ DizzyFace,
            /* 🤯 */ ExplodingHead,
            /* 🤠 */ CowboyHatFace,
            /* 🥳 */ PartyingFace,
            /* 😎 */ SmilingFaceSunglasses,
            /* 🤓 */ NerdFace,
            /* 🧐 */ FaceMonocle,
            /* 😕 */ ConfusedFace,
            /* 😟 */ WorriedFace,
            /* 🙁 */ SlightlyFrowningFace,
            /* ☹️ */ FrowningFace,
            /* 😮 */ FaceOpenMouth,
            /* 😯 */ HushedFace,
            /* 😲 */ AstonishedFace,
            /* 😳 */ FlushedFace,
            /* 🥺 */ PleadingFace,
            /* 😦 */ FrowningFaceOpenMouth,
            /* 😧 */ AnguishedFace,
            /* 😨 */ FearfulFace,
            /* 😰 */ AnxiousFaceSweat,
            /* 😥 */ SadButRelievedFace,
            /* 😢 */ CryingFace,
            /* 😭 */ LoudlyCryingFace,
            /* 😱 */ FaceScreamingFear,
            /* 😖 */ ConfoundedFace,
            /* 😣 */ PerseveringFace,
            /* 😞 */ DisappointedFace,
            /* 😓 */ DowncastFaceSweat,
            /* 😩 */ WearyFace,
            /* 😫 */ TiredFace,
            /* 🥱 */ YawningFace,
            /* 😤 */ FaceSteamFromNose,
            /* 😡 */ PoutingFace,
            /* 😠 */ AngryFace,
            /* 🤬 */ FaceSymbolsMouth,
            /* 😈 */ SmilingFaceHorns,
            /* 👿 */ AngryFaceHorns,
            /* 💀 */ Skull,
            /* ☠️ */ SkullCrossbones,
            /* 💩 */ PilePoo,
            /* 🤡 */ ClownFace,
            /* 👹 */ Ogre,
            /* 👺 */ Goblin,
            /* 👻 */ Ghost,
            /* 👽 */ Alien,
            /* 👾 */ AlienMonster,
            /* 🤖 */ Robot,
            /* 😺 */ GrinningCat,
            /* 😸 */ GrinningCatSmilingEyes,
            /* 😹 */ CatTearsJoy,
            /* 😻 */ SmilingCatHeartEyes,
            /* 😼 */ CatWrySmile,
            /* 😽 */ KissingCat,
            /* 🙀 */ WearyCat,
            /* 😿 */ CryingCat,
            /* 😾 */ PoutingCat,
            /* 🙈 */ SeeNoEvilMonkey,
            /* 🙉 */ HearNoEvilMonkey,
            /* 🙊 */ SpeakNoEvilMonkey,
            /* 💋 */ KissMark,
            /* 💌 */ LoveLetter,
            /* 💘 */ HeartArrow,
            /* 💝 */ HeartRibbon,
            /* 💖 */ SparklingHeart,
            /* 💗 */ GrowingHeart,
            /* 💓 */ BeatingHeart,
            /* 💞 */ RevolvingHearts,
            /* 💕 */ TwoHearts,
            /* 💟 */ HeartDecoration,
            /* ❣️ */ HeartExclamation,
            /* 💔 */ BrokenHeart,
            /* ❤️ */ RedHeart,
            /* 🧡 */ OrangeHeart,
            /* 💛 */ YellowHeart,
            /* 💚 */ GreenHeart,
            /* 💙 */ BlueHeart,
            /* 💜 */ PurpleHeart,
            /* 🤎 */ BrownHeart,
            /* 🖤 */ BlackHeart,
            /* 🤍 */ WhiteHeart,
            /* 💯 */ HundredPoints,
            /* 💢 */ AngerSymbol,
            /* 💥 */ Collision,
            /* 💫 */ Dizzy,
            /* 💦 */ SweatDroplets,
            /* 💨 */ DashingAway,
            /* 🕳️ */ Hole,
            /* 💣 */ Bomb,
            /* 💬 */ SpeechBalloon,
            /* 👁️‍🗨️ */ EyeSpeechBubble,
            /* 🗨️ */ LeftSpeechBubble,
            /* 🗯️ */ RightAngerBubble,
            /* 💭 */ ThoughtBalloon,
            /* 💤 */ Zzz,
        };
    }
}
