// This class is a part of the fork from neosmarts unicode.net (https://github.com/neosmart/unicode.net)
// Source: https://github.com/UWPX/unicode.net
// Original license:
// MIT License:
// https://github.com/UWPX/unicode.net/blob/master/LICENSE

using System.Collections.Generic;

namespace NeoSmart.Unicode
{
    // This file is machine-generated based on the official Unicode Consortium publication (https://unicode.org/Public/emoji/12.0/emoji-test.txt).
    // See https://github.com/UWPX/Emoji-List-Parser for the generator.
    public static partial class Emoji
    {
        /// <summary>
        /// A (sorted) enumeration of all emoji in group: OBJECTS
        /// Only contains fully-qualified and component emoji.
        /// <summary>
#if NET20 || NET30 || NET35
        public static readonly List<SingleEmoji> Objects = new List<SingleEmoji>() {
#else
        public static SortedSet<SingleEmoji> Objects => new SortedSet<SingleEmoji>() {
#endif
            /* 👓 */ Glasses,
            /* 🕶️ */ Sunglasses,
            /* 🥽 */ Goggles,
            /* 🥼 */ LabCoat,
            /* 🦺 */ SafetyVest,
            /* 👔 */ Necktie,
            /* 👕 */ TShirt,
            /* 👖 */ Jeans,
            /* 🧣 */ Scarf,
            /* 🧤 */ Gloves,
            /* 🧥 */ Coat,
            /* 🧦 */ Socks,
            /* 👗 */ Dress,
            /* 👘 */ Kimono,
            /* 🥻 */ Sari,
            /* 🩱 */ OnePieceSwimsuit,
            /* 🩲 */ SwimBrief,
            /* 🩳 */ Shorts,
            /* 👙 */ Bikini,
            /* 👚 */ WomansClothes,
            /* 👛 */ Purse,
            /* 👜 */ Handbag,
            /* 👝 */ ClutchBag,
            /* 🛍️ */ ShoppingBags,
            /* 🎒 */ Backpack,
            /* 👞 */ MansShoe,
            /* 👟 */ RunningShoe,
            /* 🥾 */ HikingBoot,
            /* 🥿 */ FlatShoe,
            /* 👠 */ HighHeeledShoe,
            /* 👡 */ WomansSandal,
            /* 🩰 */ BalletShoes,
            /* 👢 */ WomansBoot,
            /* 👑 */ Crown,
            /* 👒 */ WomansHat,
            /* 🎩 */ TopHat,
            /* 🎓 */ GraduationCap,
            /* 🧢 */ BilledCap,
            /* ⛑️ */ RescueWorkersHelmet,
            /* 📿 */ PrayerBeads,
            /* 💄 */ Lipstick,
            /* 💍 */ Ring,
            /* 💎 */ GemStone,
            /* 🔇 */ MutedSpeaker,
            /* 🔈 */ SpeakerLowVolume,
            /* 🔉 */ SpeakerMediumVolume,
            /* 🔊 */ SpeakerHighVolume,
            /* 📢 */ Loudspeaker,
            /* 📣 */ Megaphone,
            /* 📯 */ PostalHorn,
            /* 🔔 */ Bell,
            /* 🔕 */ BellSlash,
            /* 🎼 */ MusicalScore,
            /* 🎵 */ MusicalNote,
            /* 🎶 */ MusicalNotes,
            /* 🎙️ */ StudioMicrophone,
            /* 🎚️ */ LevelSlider,
            /* 🎛️ */ ControlKnobs,
            /* 🎤 */ Microphone,
            /* 🎧 */ Headphone,
            /* 📻 */ Radio,
            /* 🎷 */ Saxophone,
            /* 🎸 */ Guitar,
            /* 🎹 */ MusicalKeyboard,
            /* 🎺 */ Trumpet,
            /* 🎻 */ Violin,
            /* 🪕 */ Banjo,
            /* 🥁 */ Drum,
            /* 📱 */ MobilePhone,
            /* 📲 */ MobilePhoneArrow,
            /* ☎️ */ Telephone,
            /* 📞 */ TelephoneReceiver,
            /* 📟 */ Pager,
            /* 📠 */ FaxMachine,
            /* 🔋 */ Battery,
            /* 🔌 */ ElectricPlug,
            /* 💻 */ LaptopComputer,
            /* 🖥️ */ DesktopComputer,
            /* 🖨️ */ Printer,
            /* ⌨️ */ Keyboard,
            /* 🖱️ */ ComputerMouse,
            /* 🖲️ */ Trackball,
            /* 💽 */ ComputerDisk,
            /* 💾 */ FloppyDisk,
            /* 💿 */ OpticalDisk,
            /* 📀 */ Dvd,
            /* 🧮 */ Abacus,
            /* 🎥 */ MovieCamera,
            /* 🎞️ */ FilmFrames,
            /* 📽️ */ FilmProjector,
            /* 🎬 */ ClapperBoard,
            /* 📺 */ Television,
            /* 📷 */ Camera,
            /* 📸 */ CameraFlash,
            /* 📹 */ VideoCamera,
            /* 📼 */ Videocassette,
            /* 🔍 */ MagnifyingGlassTiltedLeft,
            /* 🔎 */ MagnifyingGlassTiltedRight,
            /* 🕯️ */ Candle,
            /* 💡 */ LightBulb,
            /* 🔦 */ Flashlight,
            /* 🏮 */ RedPaperLantern,
            /* 🪔 */ DiyaLamp,
            /* 📔 */ NotebookDecorativeCover,
            /* 📕 */ ClosedBook,
            /* 📖 */ OpenBook,
            /* 📗 */ GreenBook,
            /* 📘 */ BlueBook,
            /* 📙 */ OrangeBook,
            /* 📚 */ Books,
            /* 📓 */ Notebook,
            /* 📒 */ Ledger,
            /* 📃 */ PageCurl,
            /* 📜 */ Scroll,
            /* 📄 */ PageFacingUp,
            /* 📰 */ Newspaper,
            /* 🗞️ */ RolledUpNewspaper,
            /* 📑 */ BookmarkTabs,
            /* 🔖 */ Bookmark,
            /* 🏷️ */ Label,
            /* 💰 */ MoneyBag,
            /* 💴 */ YenBanknote,
            /* 💵 */ DollarBanknote,
            /* 💶 */ EuroBanknote,
            /* 💷 */ PoundBanknote,
            /* 💸 */ MoneyWings,
            /* 💳 */ CreditCard,
            /* 🧾 */ Receipt,
            /* 💹 */ ChartIncreasingYen,
            /* 💱 */ CurrencyExchange,
            /* 💲 */ HeavyDollarSign,
            /* ✉️ */ Envelope,
            /* 📧 */ EMail,
            /* 📨 */ IncomingEnvelope,
            /* 📩 */ EnvelopeArrow,
            /* 📤 */ OutboxTray,
            /* 📥 */ InboxTray,
            /* 📦 */ Package,
            /* 📫 */ ClosedMailboxRaisedFlag,
            /* 📪 */ ClosedMailboxLoweredFlag,
            /* 📬 */ OpenMailboxRaisedFlag,
            /* 📭 */ OpenMailboxLoweredFlag,
            /* 📮 */ Postbox,
            /* 🗳️ */ BallotBoxBallot,
            /* ✏️ */ Pencil,
            /* ✒️ */ BlackNib,
            /* 🖋️ */ FountainPen,
            /* 🖊️ */ Pen,
            /* 🖌️ */ Paintbrush,
            /* 🖍️ */ Crayon,
            /* 📝 */ Memo,
            /* 💼 */ Briefcase,
            /* 📁 */ FileFolder,
            /* 📂 */ OpenFileFolder,
            /* 🗂️ */ CardIndexDividers,
            /* 📅 */ Calendar,
            /* 📆 */ TearOffCalendar,
            /* 🗒️ */ SpiralNotepad,
            /* 🗓️ */ SpiralCalendar,
            /* 📇 */ CardIndex,
            /* 📈 */ ChartIncreasing,
            /* 📉 */ ChartDecreasing,
            /* 📊 */ BarChart,
            /* 📋 */ Clipboard,
            /* 📌 */ Pushpin,
            /* 📍 */ RoundPushpin,
            /* 📎 */ Paperclip,
            /* 🖇️ */ LinkedPaperclips,
            /* 📏 */ StraightRuler,
            /* 📐 */ TriangularRuler,
            /* ✂️ */ Scissors,
            /* 🗃️ */ CardFileBox,
            /* 🗄️ */ FileCabinet,
            /* 🗑️ */ Wastebasket,
            /* 🔒 */ Locked,
            /* 🔓 */ Unlocked,
            /* 🔏 */ LockedPen,
            /* 🔐 */ LockedKey,
            /* 🔑 */ Key,
            /* 🗝️ */ OldKey,
            /* 🔨 */ Hammer,
            /* 🪓 */ Axe,
            /* ⛏️ */ Pick,
            /* ⚒️ */ HammerPick,
            /* 🛠️ */ HammerWrench,
            /* 🗡️ */ Dagger,
            /* ⚔️ */ CrossedSwords,
            /* 🔫 */ Pistol,
            /* 🏹 */ BowArrow,
            /* 🛡️ */ Shield,
            /* 🔧 */ Wrench,
            /* 🔩 */ NutBolt,
            /* ⚙️ */ Gear,
            /* 🗜️ */ Clamp,
            /* ⚖️ */ BalanceScale,
            /* 🦯 */ ProbingCane,
            /* 🔗 */ Link,
            /* ⛓️ */ Chains,
            /* 🧰 */ Toolbox,
            /* 🧲 */ Magnet,
            /* ⚗️ */ Alembic,
            /* 🧪 */ TestTube,
            /* 🧫 */ PetriDish,
            /* 🧬 */ Dna,
            /* 🔬 */ Microscope,
            /* 🔭 */ Telescope,
            /* 📡 */ SatelliteAntenna,
            /* 💉 */ Syringe,
            /* 🩸 */ DropBlood,
            /* 💊 */ Pill,
            /* 🩹 */ AdhesiveBandage,
            /* 🩺 */ Stethoscope,
            /* 🚪 */ Door,
            /* 🛏️ */ Bed,
            /* 🛋️ */ CouchLamp,
            /* 🪑 */ Chair,
            /* 🚽 */ Toilet,
            /* 🚿 */ Shower,
            /* 🛁 */ Bathtub,
            /* 🪒 */ Razor,
            /* 🧴 */ LotionBottle,
            /* 🧷 */ SafetyPin,
            /* 🧹 */ Broom,
            /* 🧺 */ Basket,
            /* 🧻 */ RollPaper,
            /* 🧼 */ Soap,
            /* 🧽 */ Sponge,
            /* 🧯 */ FireExtinguisher,
            /* 🛒 */ ShoppingCart,
            /* 🚬 */ Cigarette,
            /* ⚰️ */ Coffin,
            /* ⚱️ */ FuneralUrn,
            /* 🗿 */ Moai,
        };
    }
}
