// This class is a part of the fork from neosmarts unicode.net (https://github.com/neosmart/unicode.net)
// Source: https://github.com/UWPX/unicode.net
// Original license:
// MIT License:
// https://github.com/UWPX/unicode.net/blob/master/LICENSE

using System.Collections.Generic;

namespace NeoSmart.Unicode
{
    // This file is machine-generated based on the official Unicode Consortium publication (https://unicode.org/Public/emoji/12.0/emoji-test.txt).
    // See https://github.com/UWPX/Emoji-List-Parser for the generator.
    public static partial class Emoji
    {
        /// <summary>
        /// A (sorted) enumeration of all emoji in group: SYMBOLS
        /// Only contains fully-qualified and component emoji.
        /// <summary>
#if NET20 || NET30 || NET35
		public static readonly List<SingleEmoji> Symbols = new List<SingleEmoji>() {
#else
        public static SortedSet<SingleEmoji> Symbols => new SortedSet<SingleEmoji>() {
#endif
			/* 🏧 */ AtmSign,
			/* 🚮 */ LitterBinSign,
			/* 🚰 */ PotableWater,
			/* ♿ */ WheelchairSymbol,
			/* 🚹 */ MensRoom,
			/* 🚺 */ WomensRoom,
			/* 🚻 */ Restroom,
			/* 🚼 */ BabySymbol,
			/* 🚾 */ WaterCloset,
			/* 🛂 */ PassportControl,
			/* 🛃 */ Customs,
			/* 🛄 */ BaggageClaim,
			/* 🛅 */ LeftLuggage,
			/* ⚠️ */ Warning,
			/* 🚸 */ ChildrenCrossing,
			/* ⛔ */ NoEntry,
			/* 🚫 */ Prohibited,
			/* 🚳 */ NoBicycles,
			/* 🚭 */ NoSmoking,
			/* 🚯 */ NoLittering,
			/* 🚱 */ NonPotableWater,
			/* 🚷 */ NoPedestrians,
			/* 📵 */ NoMobilePhones,
			/* 🔞 */ NoOneUnderEighteen,
			/* ☢️ */ Radioactive,
			/* ☣️ */ Biohazard,
			/* ⬆️ */ UpArrow,
			/* ↗️ */ UpRightArrow,
			/* ➡️ */ RightArrow,
			/* ↘️ */ DownRightArrow,
			/* ⬇️ */ DownArrow,
			/* ↙️ */ DownLeftArrow,
			/* ⬅️ */ LeftArrow,
			/* ↖️ */ UpLeftArrow,
			/* ↕️ */ UpDownArrow,
			/* ↔️ */ LeftRightArrow,
			/* ↩️ */ RightArrowCurvingLeft,
			/* ↪️ */ LeftArrowCurvingRight,
			/* ⤴️ */ RightArrowCurvingUp,
			/* ⤵️ */ RightArrowCurvingDown,
			/* 🔃 */ ClockwiseVerticalArrows,
			/* 🔄 */ CounterclockwiseArrowsButton,
			/* 🔙 */ BackArrow,
			/* 🔚 */ EndArrow,
			/* 🔛 */ OnArrow,
			/* 🔜 */ SoonArrow,
			/* 🔝 */ TopArrow,
			/* 🛐 */ PlaceWorship,
			/* ⚛️ */ AtomSymbol,
			/* 🕉️ */ Om,
			/* ✡️ */ StarDavid,
			/* ☸️ */ WheelDharma,
			/* ☯️ */ YinYang,
			/* ✝️ */ LatinCross,
			/* ☦️ */ OrthodoxCross,
			/* ☪️ */ StarCrescent,
			/* ☮️ */ PeaceSymbol,
			/* 🕎 */ Menorah,
			/* 🔯 */ DottedSixPointedStar,
			/* ♈ */ Aries,
			/* ♉ */ Taurus,
			/* ♊ */ Gemini,
			/* ♋ */ Cancer,
			/* ♌ */ Leo,
			/* ♍ */ Virgo,
			/* ♎ */ Libra,
			/* ♏ */ Scorpio,
			/* ♐ */ Sagittarius,
			/* ♑ */ Capricorn,
			/* ♒ */ Aquarius,
			/* ♓ */ Pisces,
			/* ⛎ */ Ophiuchus,
			/* 🔀 */ ShuffleTracksButton,
			/* 🔁 */ RepeatButton,
			/* 🔂 */ RepeatSingleButton,
			/* ▶️ */ PlayButton,
			/* ⏩ */ FastForwardButton,
			/* ⏭️ */ NextTrackButton,
			/* ⏯️ */ PlayPauseButton,
			/* ◀️ */ ReverseButton,
			/* ⏪ */ FastReverseButton,
			/* ⏮️ */ LastTrackButton,
			/* 🔼 */ UpwardsButton,
			/* ⏫ */ FastUpButton,
			/* 🔽 */ DownwardsButton,
			/* ⏬ */ FastDownButton,
			/* ⏸️ */ PauseButton,
			/* ⏹️ */ StopButton,
			/* ⏺️ */ RecordButton,
			/* ⏏️ */ EjectButton,
			/* 🎦 */ Cinema,
			/* 🔅 */ DimButton,
			/* 🔆 */ BrightButton,
			/* 📶 */ AntennaBars,
			/* 📳 */ VibrationMode,
			/* 📴 */ MobilePhoneOff,
			/* ♀️ */ FemaleSign,
			/* ♂️ */ MaleSign,
			/* ⚕️ */ MedicalSymbol,
			/* ♾️ */ Infinity,
			/* ♻️ */ RecyclingSymbol,
			/* ⚜️ */ FleurDeLis,
			/* 🔱 */ TridentEmblem,
			/* 📛 */ NameBadge,
			/* 🔰 */ JapaneseSymbolForBeginner,
			/* ⭕ */ HollowRedCircle,
			/* ✅ */ CheckMarkButton,
			/* ☑️ */ CheckBoxCheck,
			/* ✔️ */ CheckMark,
			/* ✖️ */ MultiplicationSign,
			/* ❌ */ CrossMark,
			/* ❎ */ CrossMarkButton,
			/* ➕ */ PlusSign,
			/* ➖ */ MinusSign,
			/* ➗ */ DivisionSign,
			/* ➰ */ CurlyLoop,
			/* ➿ */ DoubleCurlyLoop,
			/* 〽️ */ PartAlternationMark,
			/* ✳️ */ EightSpokedAsterisk,
			/* ✴️ */ EightPointedStar,
			/* ❇️ */ Sparkle,
			/* ‼️ */ DoubleExclamationMark,
			/* ⁉️ */ ExclamationQuestionMark,
			/* ❓ */ QuestionMark,
			/* ❔ */ WhiteQuestionMark,
			/* ❕ */ WhiteExclamationMark,
			/* ❗ */ ExclamationMark,
			/* 〰️ */ WavyDash,
			/* ©️ */ Copyright,
			/* ®️ */ Registered,
			/* ™️ */ TradeMark,
			/* ️⃣ */ KeycapHash,
			/* *️⃣ */ KeycapAsterisk,
			/* 0️⃣ */ Keycap0,
			/* 1️⃣ */ Keycap1,
			/* 2️⃣ */ Keycap2,
			/* 3️⃣ */ Keycap3,
			/* 4️⃣ */ Keycap4,
			/* 5️⃣ */ Keycap5,
			/* 6️⃣ */ Keycap6,
			/* 7️⃣ */ Keycap7,
			/* 8️⃣ */ Keycap8,
			/* 9️⃣ */ Keycap9,
			/* 🔟 */ Keycap10,
			/* 🔠 */ InputLatinUppercase,
			/* 🔡 */ InputLatinLowercase,
			/* 🔢 */ InputNumbers,
			/* 🔣 */ InputSymbols,
			/* 🔤 */ InputLatinLetters,
			/* 🅰️ */ AButtonBloodType,
			/* 🆎 */ AbButtonBloodType,
			/* 🅱️ */ BButtonBloodType,
			/* 🆑 */ ClButton,
			/* 🆒 */ CoolButton,
			/* 🆓 */ FreeButton,
			/* ℹ️ */ Information,
			/* 🆔 */ IdButton,
			/* Ⓜ️ */ CircledM,
			/* 🆕 */ NewButton,
			/* 🆖 */ NgButton,
			/* 🅾️ */ OButtonBloodType,
			/* 🆗 */ OkButton,
			/* 🅿️ */ PButton,
			/* 🆘 */ SosButton,
			/* 🆙 */ UpButton,
			/* 🆚 */ VsButton,
			/* 🈁 */ JapaneseHereButton,
			/* 🈂️ */ JapaneseServiceChargeButton,
			/* 🈷️ */ JapaneseMonthlyAmountButton,
			/* 🈶 */ JapaneseNotFreeChargeButton,
			/* 🈯 */ JapaneseReservedButton,
			/* 🉐 */ JapaneseBargainButton,
			/* 🈹 */ JapaneseDiscountButton,
			/* 🈚 */ JapaneseFreeChargeButton,
			/* 🈲 */ JapaneseProhibitedButton,
			/* 🉑 */ JapaneseAcceptableButton,
			/* 🈸 */ JapaneseApplicationButton,
			/* 🈴 */ JapanesePassingGradeButton,
			/* 🈳 */ JapaneseVacancyButton,
			/* ㊗️ */ JapaneseCongratulationsButton,
			/* ㊙️ */ JapaneseSecretButton,
			/* 🈺 */ JapaneseOpenForBusinessButton,
			/* 🈵 */ JapaneseNoVacancyButton,
			/* 🔴 */ RedCircle,
			/* 🟠 */ OrangeCircle,
			/* 🟡 */ YellowCircle,
			/* 🟢 */ GreenCircle,
			/* 🔵 */ BlueCircle,
			/* 🟣 */ PurpleCircle,
			/* 🟤 */ BrownCircle,
			/* ⚫ */ BlackCircle,
			/* ⚪ */ WhiteCircle,
			/* 🟥 */ RedSquare,
			/* 🟧 */ OrangeSquare,
			/* 🟨 */ YellowSquare,
			/* 🟩 */ GreenSquare,
			/* 🟦 */ BlueSquare,
			/* 🟪 */ PurpleSquare,
			/* 🟫 */ BrownSquare,
			/* ⬛ */ BlackLargeSquare,
			/* ⬜ */ WhiteLargeSquare,
			/* ◼️ */ BlackMediumSquare,
			/* ◻️ */ WhiteMediumSquare,
			/* ◾ */ BlackMediumSmallSquare,
			/* ◽ */ WhiteMediumSmallSquare,
			/* ▪️ */ BlackSmallSquare,
			/* ▫️ */ WhiteSmallSquare,
			/* 🔶 */ LargeOrangeDiamond,
			/* 🔷 */ LargeBlueDiamond,
			/* 🔸 */ SmallOrangeDiamond,
			/* 🔹 */ SmallBlueDiamond,
			/* 🔺 */ RedTrianglePointedUp,
			/* 🔻 */ RedTrianglePointedDown,
			/* 💠 */ DiamondADot,
			/* 🔘 */ RadioButton,
			/* 🔳 */ WhiteSquareButton,
			/* 🔲 */ BlackSquareButton,
        };
    }
}
