// This class is a part of the fork from neosmarts unicode.net (https://github.com/neosmart/unicode.net)
// Source: https://github.com/UWPX/unicode.net
// Original license:
// MIT License:
// https://github.com/UWPX/unicode.net/blob/master/LICENSE

using System.Collections.Generic;

namespace NeoSmart.Unicode
{
    // This file is machine-generated based on the official Unicode Consortium publication (https://unicode.org/Public/emoji/12.0/emoji-test.txt).
    // See https://github.com/UWPX/Emoji-List-Parser for the generator.
    public static partial class Emoji
    {
        /// <summary>
        /// A (sorted) enumeration of all emoji in group: FOOD_AND_DRINK
        /// Only contains fully-qualified and component emoji.
        /// <summary>
#if NET20 || NET30 || NET35
		public static readonly List<SingleEmoji> FoodAndDrink = new List<SingleEmoji>() {
#else
        public static SortedSet<SingleEmoji> FoodAndDrink => new SortedSet<SingleEmoji>() {
#endif
			/* 🍇 */ Grapes,
			/* 🍈 */ Melon,
			/* 🍉 */ Watermelon,
			/* 🍊 */ Tangerine,
			/* 🍋 */ Lemon,
			/* 🍌 */ Banana,
			/* 🍍 */ Pineapple,
			/* 🥭 */ Mango,
			/* 🍎 */ RedApple,
			/* 🍏 */ GreenApple,
			/* 🍐 */ Pear,
			/* 🍑 */ Peach,
			/* 🍒 */ Cherries,
			/* 🍓 */ Strawberry,
			/* 🥝 */ KiwiFruit,
			/* 🍅 */ Tomato,
			/* 🥥 */ Coconut,
			/* 🥑 */ Avocado,
			/* 🍆 */ Eggplant,
			/* 🥔 */ Potato,
			/* 🥕 */ Carrot,
			/* 🌽 */ EarCorn,
			/* 🌶️ */ HotPepper,
			/* 🥒 */ Cucumber,
			/* 🥬 */ LeafyGreen,
			/* 🥦 */ Broccoli,
			/* 🧄 */ Garlic,
			/* 🧅 */ Onion,
			/* 🍄 */ Mushroom,
			/* 🥜 */ Peanuts,
			/* 🌰 */ Chestnut,
			/* 🍞 */ Bread,
			/* 🥐 */ Croissant,
			/* 🥖 */ BaguetteBread,
			/* 🥨 */ Pretzel,
			/* 🥯 */ Bagel,
			/* 🥞 */ Pancakes,
			/* 🧇 */ Waffle,
			/* 🧀 */ CheeseWedge,
			/* 🍖 */ MeatBone,
			/* 🍗 */ PoultryLeg,
			/* 🥩 */ CutMeat,
			/* 🥓 */ Bacon,
			/* 🍔 */ Hamburger,
			/* 🍟 */ FrenchFries,
			/* 🍕 */ Pizza,
			/* 🌭 */ HotDog,
			/* 🥪 */ Sandwich,
			/* 🌮 */ Taco,
			/* 🌯 */ Burrito,
			/* 🥙 */ StuffedFlatbread,
			/* 🧆 */ Falafel,
			/* 🥚 */ Egg,
			/* 🍳 */ Cooking,
			/* 🥘 */ ShallowPanFood,
			/* 🍲 */ PotFood,
			/* 🥣 */ BowlSpoon,
			/* 🥗 */ GreenSalad,
			/* 🍿 */ Popcorn,
			/* 🧈 */ Butter,
			/* 🧂 */ Salt,
			/* 🥫 */ CannedFood,
			/* 🍱 */ BentoBox,
			/* 🍘 */ RiceCracker,
			/* 🍙 */ RiceBall,
			/* 🍚 */ CookedRice,
			/* 🍛 */ CurryRice,
			/* 🍜 */ SteamingBowl,
			/* 🍝 */ Spaghetti,
			/* 🍠 */ RoastedSweetPotato,
			/* 🍢 */ Oden,
			/* 🍣 */ Sushi,
			/* 🍤 */ FriedShrimp,
			/* 🍥 */ FishCakeSwirl,
			/* 🥮 */ MoonCake,
			/* 🍡 */ Dango,
			/* 🥟 */ Dumpling,
			/* 🥠 */ FortuneCookie,
			/* 🥡 */ TakeoutBox,
			/* 🦀 */ Crab,
			/* 🦞 */ Lobster,
			/* 🦐 */ Shrimp,
			/* 🦑 */ Squid,
			/* 🦪 */ Oyster,
			/* 🍦 */ SoftIceCream,
			/* 🍧 */ ShavedIce,
			/* 🍨 */ IceCream,
			/* 🍩 */ Doughnut,
			/* 🍪 */ Cookie,
			/* 🎂 */ BirthdayCake,
			/* 🍰 */ Shortcake,
			/* 🧁 */ Cupcake,
			/* 🥧 */ Pie,
			/* 🍫 */ ChocolateBar,
			/* 🍬 */ Candy,
			/* 🍭 */ Lollipop,
			/* 🍮 */ Custard,
			/* 🍯 */ HoneyPot,
			/* 🍼 */ BabyBottle,
			/* 🥛 */ GlassMilk,
			/* ☕ */ HotBeverage,
			/* 🍵 */ TeacupHandle,
			/* 🍶 */ Sake,
			/* 🍾 */ BottlePoppingCork,
			/* 🍷 */ WineGlass,
			/* 🍸 */ CocktailGlass,
			/* 🍹 */ TropicalDrink,
			/* 🍺 */ BeerMug,
			/* 🍻 */ ClinkingBeerMugs,
			/* 🥂 */ ClinkingGlasses,
			/* 🥃 */ TumblerGlass,
			/* 🥤 */ CupStraw,
			/* 🧃 */ BeverageBox,
			/* 🧉 */ Mate,
			/* 🧊 */ IceCube,
			/* 🥢 */ Chopsticks,
			/* 🍽️ */ ForkKnifePlate,
			/* 🍴 */ ForkKnife,
			/* 🥄 */ Spoon,
			/* 🔪 */ KitchenKnife,
			/* 🏺 */ Amphora,
        };
    }
}
