using System.Collections.Generic;

namespace NeoSmart.Unicode
{
    // This file is machine-generated based on the official Unicode Consortium publication (https://unicode.org/Public/emoji/14.0/emoji-test.txt).
    // See https://github.com/UWPX/Emoji-List-Parser for the generator.
    public static partial class Emoji
    {
        /// <summary>
        /// A (sorted) enumeration of all emoji in group: SMILEYS_AND_EMOTION
        /// Only contains fully-qualified and component emoji.
        /// <summary>
#if NET20 || NET30 || NET35
        public static readonly List<SingleEmoji> SmileysAndEmotion = new List<SingleEmoji>() {
#else
        public static SortedSet<SingleEmoji> SmileysAndEmotion => new SortedSet<SingleEmoji>() {
#endif
            /* 😀 */ GrinningFace_E1_0,
            /* 😃 */ GrinningFaceBigEyes_E0_6,
            /* 😄 */ GrinningFaceSmilingEyes_E0_6,
            /* 😁 */ BeamingFaceSmilingEyes_E0_6,
            /* 😆 */ GrinningSquintingFace_E0_6,
            /* 😅 */ GrinningFaceSweat_E0_6,
            /* 🤣 */ RollingFloorLaughing_E3_0,
            /* 😂 */ FaceTearsJoy_E0_6,
            /* 🙂 */ SlightlySmilingFace_E1_0,
            /* 🙃 */ UpsideDownFace_E1_0,
            /* 🫠 */ MeltingFace_E14_0,
            /* 😉 */ WinkingFace_E0_6,
            /* 😊 */ SmilingFaceSmilingEyes_E0_6,
            /* 😇 */ SmilingFaceHalo_E1_0,
            /* 🥰 */ SmilingFaceHearts_E11_0,
            /* 😍 */ SmilingFaceHeartEyes_E0_6,
            /* 🤩 */ StarStruck_E5_0,
            /* 😘 */ FaceBlowingAKiss_E0_6,
            /* 😗 */ KissingFace_E1_0,
            /* ☺️ */ SmilingFace_E0_6,
            /* 😚 */ KissingFaceClosedEyes_E0_6,
            /* 😙 */ KissingFaceSmilingEyes_E1_0,
            /* 🥲 */ SmilingFaceTear_E13_0,
            /* 😋 */ FaceSavoringFood_E0_6,
            /* 😛 */ FaceTongue_E1_0,
            /* 😜 */ WinkingFaceTongue_E0_6,
            /* 🤪 */ ZanyFace_E5_0,
            /* 😝 */ SquintingFaceTongue_E0_6,
            /* 🤑 */ MoneyMouthFace_E1_0,
            /* 🤗 */ SmilingFaceOpenHands_E1_0,
            /* 🤭 */ FaceHandOverMouth_E5_0,
            /* 🫢 */ FaceOpenEyesHandOverMouth_E14_0,
            /* 🫣 */ FacePeekingEye_E14_0,
            /* 🤫 */ ShushingFace_E5_0,
            /* 🤔 */ ThinkingFace_E1_0,
            /* 🫡 */ SalutingFace_E14_0,
            /* 🤐 */ ZipperMouthFace_E1_0,
            /* 🤨 */ FaceRaisedEyebrow_E5_0,
            /* 😐 */ NeutralFace_E0_7,
            /* 😑 */ ExpressionlessFace_E1_0,
            /* 😶 */ FaceMouth_E1_0,
            /* 🫥 */ DottedLineFace_E14_0,
            /* 😶‍🌫️ */ FaceClouds_E13_1,
            /* 😏 */ SmirkingFace_E0_6,
            /* 😒 */ UnamusedFace_E0_6,
            /* 🙄 */ FaceRollingEyes_E1_0,
            /* 😬 */ GrimacingFace_E1_0,
            /* 😮‍💨 */ FaceExhaling_E13_1,
            /* 🤥 */ LyingFace_E3_0,
            /* 😌 */ RelievedFace_E0_6,
            /* 😔 */ PensiveFace_E0_6,
            /* 😪 */ SleepyFace_E0_6,
            /* 🤤 */ DroolingFace_E3_0,
            /* 😴 */ SleepingFace_E1_0,
            /* 😷 */ FaceMedicalMask_E0_6,
            /* 🤒 */ FaceThermometer_E1_0,
            /* 🤕 */ FaceHeadBandage_E1_0,
            /* 🤢 */ NauseatedFace_E3_0,
            /* 🤮 */ FaceVomiting_E5_0,
            /* 🤧 */ SneezingFace_E3_0,
            /* 🥵 */ HotFace_E11_0,
            /* 🥶 */ ColdFace_E11_0,
            /* 🥴 */ WoozyFace_E11_0,
            /* 😵 */ FaceCrossedOutEyes_E0_6,
            /* 😵‍💫 */ FaceSpiralEyes_E13_1,
            /* 🤯 */ ExplodingHead_E5_0,
            /* 🤠 */ CowboyHatFace_E3_0,
            /* 🥳 */ PartyingFace_E11_0,
            /* 🥸 */ DisguisedFace_E13_0,
            /* 😎 */ SmilingFaceSunglasses_E1_0,
            /* 🤓 */ NerdFace_E1_0,
            /* 🧐 */ FaceMonocle_E5_0,
            /* 😕 */ ConfusedFace_E1_0,
            /* 🫤 */ FaceDiagonalMouth_E14_0,
            /* 😟 */ WorriedFace_E1_0,
            /* 🙁 */ SlightlyFrowningFace_E1_0,
            /* ☹️ */ FrowningFace_E0_7,
            /* 😮 */ FaceOpenMouth_E1_0,
            /* 😯 */ HushedFace_E1_0,
            /* 😲 */ AstonishedFace_E0_6,
            /* 😳 */ FlushedFace_E0_6,
            /* 🥺 */ PleadingFace_E11_0,
            /* 🥹 */ FaceHoldingBackTears_E14_0,
            /* 😦 */ FrowningFaceOpenMouth_E1_0,
            /* 😧 */ AnguishedFace_E1_0,
            /* 😨 */ FearfulFace_E0_6,
            /* 😰 */ AnxiousFaceSweat_E0_6,
            /* 😥 */ SadButRelievedFace_E0_6,
            /* 😢 */ CryingFace_E0_6,
            /* 😭 */ LoudlyCryingFace_E0_6,
            /* 😱 */ FaceScreamingFear_E0_6,
            /* 😖 */ ConfoundedFace_E0_6,
            /* 😣 */ PerseveringFace_E0_6,
            /* 😞 */ DisappointedFace_E0_6,
            /* 😓 */ DowncastFaceSweat_E0_6,
            /* 😩 */ WearyFace_E0_6,
            /* 😫 */ TiredFace_E0_6,
            /* 🥱 */ YawningFace_E12_0,
            /* 😤 */ FaceSteamFromNose_E0_6,
            /* 😡 */ PoutingFace_E0_6,
            /* 😠 */ AngryFace_E0_6,
            /* 🤬 */ FaceSymbolsMouth_E5_0,
            /* 😈 */ SmilingFaceHorns_E1_0,
            /* 👿 */ AngryFaceHorns_E0_6,
            /* 💀 */ Skull_E0_6,
            /* ☠️ */ SkullCrossbones_E1_0,
            /* 💩 */ PilePoo_E0_6,
            /* 🤡 */ ClownFace_E3_0,
            /* 👹 */ Ogre_E0_6,
            /* 👺 */ Goblin_E0_6,
            /* 👻 */ Ghost_E0_6,
            /* 👽 */ Alien_E0_6,
            /* 👾 */ AlienMonster_E0_6,
            /* 🤖 */ Robot_E1_0,
            /* 😺 */ GrinningCat_E0_6,
            /* 😸 */ GrinningCatSmilingEyes_E0_6,
            /* 😹 */ CatTearsJoy_E0_6,
            /* 😻 */ SmilingCatHeartEyes_E0_6,
            /* 😼 */ CatWrySmile_E0_6,
            /* 😽 */ KissingCat_E0_6,
            /* 🙀 */ WearyCat_E0_6,
            /* 😿 */ CryingCat_E0_6,
            /* 😾 */ PoutingCat_E0_6,
            /* 🙈 */ SeeNoEvilMonkey_E0_6,
            /* 🙉 */ HearNoEvilMonkey_E0_6,
            /* 🙊 */ SpeakNoEvilMonkey_E0_6,
            /* 💋 */ KissMark_E0_6,
            /* 💌 */ LoveLetter_E0_6,
            /* 💘 */ HeartArrow_E0_6,
            /* 💝 */ HeartRibbon_E0_6,
            /* 💖 */ SparklingHeart_E0_6,
            /* 💗 */ GrowingHeart_E0_6,
            /* 💓 */ BeatingHeart_E0_6,
            /* 💞 */ RevolvingHearts_E0_6,
            /* 💕 */ TwoHearts_E0_6,
            /* 💟 */ HeartDecoration_E0_6,
            /* ❣️ */ HeartExclamation_E1_0,
            /* 💔 */ BrokenHeart_E0_6,
            /* ❤️‍🔥 */ HeartFire_E13_1,
            /* ❤️‍🩹 */ MendingHeart_E13_1,
            /* ❤️ */ RedHeart_E0_6,
            /* 🧡 */ OrangeHeart_E5_0,
            /* 💛 */ YellowHeart_E0_6,
            /* 💚 */ GreenHeart_E0_6,
            /* 💙 */ BlueHeart_E0_6,
            /* 💜 */ PurpleHeart_E0_6,
            /* 🤎 */ BrownHeart_E12_0,
            /* 🖤 */ BlackHeart_E3_0,
            /* 🤍 */ WhiteHeart_E12_0,
            /* 💯 */ HundredPoints_E0_6,
            /* 💢 */ AngerSymbol_E0_6,
            /* 💥 */ Collision_E0_6,
            /* 💫 */ Dizzy_E0_6,
            /* 💦 */ SweatDroplets_E0_6,
            /* 💨 */ DashingAway_E0_6,
            /* 🕳️ */ Hole_E0_7,
            /* 💣 */ Bomb_E0_6,
            /* 💬 */ SpeechBalloon_E0_6,
            /* 👁️‍🗨️ */ EyeSpeechBubble_E2_0,
            /* 🗨️ */ LeftSpeechBubble_E2_0,
            /* 🗯️ */ RightAngerBubble_E0_7,
            /* 💭 */ ThoughtBalloon_E1_0,
            /* 💤 */ Zzz_E0_6,
        };
    }
}
