using System.Collections.Generic;

namespace NeoSmart.Unicode
{
    // This file is machine-generated based on the official Unicode Consortium publication (https://unicode.org/Public/emoji/14.0/emoji-test.txt).
    // See https://github.com/UWPX/Emoji-List-Parser for the generator.
    public static partial class Emoji
    {
        /// <summary>
        /// A (sorted) enumeration of all emoji in group: ACTIVITIES
        /// Only contains fully-qualified and component emoji.
        /// <summary>
#if NET20 || NET30 || NET35
        public static readonly List<SingleEmoji> Activities = new List<SingleEmoji>() {
#else
        public static SortedSet<SingleEmoji> Activities => new SortedSet<SingleEmoji>() {
#endif
            /* 🎃 */ JackOLantern_E0_6,
            /* 🎄 */ ChristmasTree_E0_6,
            /* 🎆 */ Fireworks_E0_6,
            /* 🎇 */ Sparkler_E0_6,
            /* 🧨 */ Firecracker_E11_0,
            /* ✨ */ Sparkles_E0_6,
            /* 🎈 */ Balloon_E0_6,
            /* 🎉 */ PartyPopper_E0_6,
            /* 🎊 */ ConfettiBall_E0_6,
            /* 🎋 */ TanabataTree_E0_6,
            /* 🎍 */ PineDecoration_E0_6,
            /* 🎎 */ JapaneseDolls_E0_6,
            /* 🎏 */ CarpStreamer_E0_6,
            /* 🎐 */ WindChime_E0_6,
            /* 🎑 */ MoonViewingCeremony_E0_6,
            /* 🧧 */ RedEnvelope_E11_0,
            /* 🎀 */ Ribbon_E0_6,
            /* 🎁 */ WrappedGift_E0_6,
            /* 🎗️ */ ReminderRibbon_E0_7,
            /* 🎟️ */ AdmissionTickets_E0_7,
            /* 🎫 */ Ticket_E0_6,
            /* 🎖️ */ MilitaryMedal_E0_7,
            /* 🏆 */ Trophy_E0_6,
            /* 🏅 */ SportsMedal_E1_0,
            /* 🥇 */ FirstPlaceMedal_E3_0,
            /* 🥈 */ SecondPlaceMedal_E3_0,
            /* 🥉 */ ThirdPlaceMedal_E3_0,
            /* ⚽ */ SoccerBall_E0_6,
            /* ⚾ */ Baseball_E0_6,
            /* 🥎 */ Softball_E11_0,
            /* 🏀 */ Basketball_E0_6,
            /* 🏐 */ Volleyball_E1_0,
            /* 🏈 */ AmericanFootball_E0_6,
            /* 🏉 */ RugbyFootball_E1_0,
            /* 🎾 */ Tennis_E0_6,
            /* 🥏 */ FlyingDisc_E11_0,
            /* 🎳 */ Bowling_E0_6,
            /* 🏏 */ CricketGame_E1_0,
            /* 🏑 */ FieldHockey_E1_0,
            /* 🏒 */ IceHockey_E1_0,
            /* 🥍 */ Lacrosse_E11_0,
            /* 🏓 */ PingPong_E1_0,
            /* 🏸 */ Badminton_E1_0,
            /* 🥊 */ BoxingGlove_E3_0,
            /* 🥋 */ MartialArtsUniform_E3_0,
            /* 🥅 */ GoalNet_E3_0,
            /* ⛳ */ FlagHole_E0_6,
            /* ⛸️ */ IceSkate_E0_7,
            /* 🎣 */ FishingPole_E0_6,
            /* 🤿 */ DivingMask_E12_0,
            /* 🎽 */ RunningShirt_E0_6,
            /* 🎿 */ Skis_E0_6,
            /* 🛷 */ Sled_E5_0,
            /* 🥌 */ CurlingStone_E5_0,
            /* 🎯 */ Bullseye_E0_6,
            /* 🪀 */ YoYo_E12_0,
            /* 🪁 */ Kite_E12_0,
            /* 🎱 */ Pool8Ball_E0_6,
            /* 🔮 */ CrystalBall_E0_6,
            /* 🪄 */ MagicWand_E13_0,
            /* 🧿 */ NazarAmulet_E11_0,
            /* 🪬 */ Hamsa_E14_0,
            /* 🎮 */ VideoGame_E0_6,
            /* 🕹️ */ Joystick_E0_7,
            /* 🎰 */ SlotMachine_E0_6,
            /* 🎲 */ GameDie_E0_6,
            /* 🧩 */ PuzzlePiece_E11_0,
            /* 🧸 */ TeddyBear_E11_0,
            /* 🪅 */ Piñata_E13_0,
            /* 🪩 */ MirrorBall_E14_0,
            /* 🪆 */ NestingDolls_E13_0,
            /* ♠️ */ SpadeSuit_E0_6,
            /* ♥️ */ HeartSuit_E0_6,
            /* ♦️ */ DiamondSuit_E0_6,
            /* ♣️ */ ClubSuit_E0_6,
            /* ♟️ */ ChessPawn_E11_0,
            /* 🃏 */ Joker_E0_6,
            /* 🀄 */ MahjongRedDragon_E0_6,
            /* 🎴 */ FlowerPlayingCards_E0_6,
            /* 🎭 */ PerformingArts_E0_6,
            /* 🖼️ */ FramedPicture_E0_7,
            /* 🎨 */ ArtistPalette_E0_6,
            /* 🧵 */ Thread_E11_0,
            /* 🪡 */ SewingNeedle_E13_0,
            /* 🧶 */ Yarn_E11_0,
            /* 🪢 */ Knot_E13_0,
        };
    }
}
