using System.Collections.Generic;

namespace NeoSmart.Unicode
{
    // This file is machine-generated based on the official Unicode Consortium publication (https://unicode.org/Public/emoji/14.0/emoji-test.txt).
    // See https://github.com/UWPX/Emoji-List-Parser for the generator.
    public static partial class Emoji
    {
        /// <summary>
        /// A (sorted) enumeration of all emoji in group: ANIMALS_AND_NATURE
        /// Only contains fully-qualified and component emoji.
        /// <summary>
#if NET20 || NET30 || NET35
        public static readonly List<SingleEmoji> AnimalsAndNature = new List<SingleEmoji>() {
#else
        public static SortedSet<SingleEmoji> AnimalsAndNature => new SortedSet<SingleEmoji>() {
#endif
            /* 🐱‍👤 */ NinjaCat_E0_0,
            /* 🐱‍👓 */ HipsterCat_E0_0,
            /* 🐱‍💻 */ HackerCat_E0_0,
            /* 🐱‍🐉 */ DinoCat_E0_0,
            /* 🐱‍🏍 */ StuntCat_E0_0,
            /* 🐱‍🚀 */ AstroCat_E0_0,
            /* 🐵 */ MonkeyFace_E0_6,
            /* 🐒 */ Monkey_E0_6,
            /* 🦍 */ Gorilla_E3_0,
            /* 🦧 */ Orangutan_E12_0,
            /* 🐶 */ DogFace_E0_6,
            /* 🐕 */ Dog_E0_7,
            /* 🦮 */ GuideDog_E12_0,
            /* 🐕‍🦺 */ ServiceDog_E12_0,
            /* 🐩 */ Poodle_E0_6,
            /* 🐺 */ Wolf_E0_6,
            /* 🦊 */ Fox_E3_0,
            /* 🦝 */ Raccoon_E11_0,
            /* 🐱 */ CatFace_E0_6,
            /* 🐈 */ Cat_E0_7,
            /* 🐈‍⬛ */ BlackCat_E13_0,
            /* 🦁 */ Lion_E1_0,
            /* 🐯 */ TigerFace_E0_6,
            /* 🐅 */ Tiger_E1_0,
            /* 🐆 */ Leopard_E1_0,
            /* 🐴 */ HorseFace_E0_6,
            /* 🐎 */ Horse_E0_6,
            /* 🦄 */ Unicorn_E1_0,
            /* 🦓 */ Zebra_E5_0,
            /* 🦌 */ Deer_E3_0,
            /* 🦬 */ Bison_E13_0,
            /* 🐮 */ CowFace_E0_6,
            /* 🐂 */ Ox_E1_0,
            /* 🐃 */ WaterBuffalo_E1_0,
            /* 🐄 */ Cow_E1_0,
            /* 🐷 */ PigFace_E0_6,
            /* 🐖 */ Pig_E1_0,
            /* 🐗 */ Boar_E0_6,
            /* 🐽 */ PigNose_E0_6,
            /* 🐏 */ Ram_E1_0,
            /* 🐑 */ Ewe_E0_6,
            /* 🐐 */ Goat_E1_0,
            /* 🐪 */ Camel_E1_0,
            /* 🐫 */ TwoHumpCamel_E0_6,
            /* 🦙 */ Llama_E11_0,
            /* 🦒 */ Giraffe_E5_0,
            /* 🐘 */ Elephant_E0_6,
            /* 🦣 */ Mammoth_E13_0,
            /* 🦏 */ Rhinoceros_E3_0,
            /* 🦛 */ Hippopotamus_E11_0,
            /* 🐭 */ MouseFace_E0_6,
            /* 🐁 */ Mouse_E1_0,
            /* 🐀 */ Rat_E1_0,
            /* 🐹 */ Hamster_E0_6,
            /* 🐰 */ RabbitFace_E0_6,
            /* 🐇 */ Rabbit_E1_0,
            /* 🐿️ */ Chipmunk_E0_7,
            /* 🦫 */ Beaver_E13_0,
            /* 🦔 */ Hedgehog_E5_0,
            /* 🦇 */ Bat_E3_0,
            /* 🐻 */ Bear_E0_6,
            /* 🐻‍❄️ */ PolarBear_E13_0,
            /* 🐨 */ Koala_E0_6,
            /* 🐼 */ Panda_E0_6,
            /* 🦥 */ Sloth_E12_0,
            /* 🦦 */ Otter_E12_0,
            /* 🦨 */ Skunk_E12_0,
            /* 🦘 */ Kangaroo_E11_0,
            /* 🦡 */ Badger_E11_0,
            /* 🐾 */ PawPrints_E0_6,
            /* 🦃 */ Turkey_E1_0,
            /* 🐔 */ Chicken_E0_6,
            /* 🐓 */ Rooster_E1_0,
            /* 🐣 */ HatchingChick_E0_6,
            /* 🐤 */ BabyChick_E0_6,
            /* 🐥 */ FrontFacingBabyChick_E0_6,
            /* 🐦 */ Bird_E0_6,
            /* 🐧 */ Penguin_E0_6,
            /* 🕊️ */ Dove_E0_7,
            /* 🦅 */ Eagle_E3_0,
            /* 🦆 */ Duck_E3_0,
            /* 🦢 */ Swan_E11_0,
            /* 🦉 */ Owl_E3_0,
            /* 🦤 */ Dodo_E13_0,
            /* 🪶 */ Feather_E13_0,
            /* 🦩 */ Flamingo_E12_0,
            /* 🦚 */ Peacock_E11_0,
            /* 🦜 */ Parrot_E11_0,
            /* 🐸 */ Frog_E0_6,
            /* 🐊 */ Crocodile_E1_0,
            /* 🐢 */ Turtle_E0_6,
            /* 🦎 */ Lizard_E3_0,
            /* 🐍 */ Snake_E0_6,
            /* 🐲 */ DragonFace_E0_6,
            /* 🐉 */ Dragon_E1_0,
            /* 🦕 */ Sauropod_E5_0,
            /* 🦖 */ TRex_E5_0,
            /* 🐳 */ SpoutingWhale_E0_6,
            /* 🐋 */ Whale_E1_0,
            /* 🐬 */ Dolphin_E0_6,
            /* 🦭 */ Seal_E13_0,
            /* 🐟 */ Fish_E0_6,
            /* 🐠 */ TropicalFish_E0_6,
            /* 🐡 */ Blowfish_E0_6,
            /* 🦈 */ Shark_E3_0,
            /* 🐙 */ Octopus_E0_6,
            /* 🐚 */ SpiralShell_E0_6,
            /* 🪸 */ Coral_E14_0,
            /* 🐌 */ Snail_E0_6,
            /* 🦋 */ Butterfly_E3_0,
            /* 🐛 */ Bug_E0_6,
            /* 🐜 */ Ant_E0_6,
            /* 🐝 */ Honeybee_E0_6,
            /* 🪲 */ Beetle_E13_0,
            /* 🐞 */ LadyBeetle_E0_6,
            /* 🦗 */ Cricket_E5_0,
            /* 🪳 */ Cockroach_E13_0,
            /* 🕷️ */ Spider_E0_7,
            /* 🕸️ */ SpiderWeb_E0_7,
            /* 🦂 */ Scorpion_E1_0,
            /* 🦟 */ Mosquito_E11_0,
            /* 🪰 */ Fly_E13_0,
            /* 🪱 */ Worm_E13_0,
            /* 🦠 */ Microbe_E11_0,
            /* 💐 */ Bouquet_E0_6,
            /* 🌸 */ CherryBlossom_E0_6,
            /* 💮 */ WhiteFlower_E0_6,
            /* 🪷 */ Lotus_E14_0,
            /* 🏵️ */ Rosette_E0_7,
            /* 🌹 */ Rose_E0_6,
            /* 🥀 */ WiltedFlower_E3_0,
            /* 🌺 */ Hibiscus_E0_6,
            /* 🌻 */ Sunflower_E0_6,
            /* 🌼 */ Blossom_E0_6,
            /* 🌷 */ Tulip_E0_6,
            /* 🌱 */ Seedling_E0_6,
            /* 🪴 */ PottedPlant_E13_0,
            /* 🌲 */ EvergreenTree_E1_0,
            /* 🌳 */ DeciduousTree_E1_0,
            /* 🌴 */ PalmTree_E0_6,
            /* 🌵 */ Cactus_E0_6,
            /* 🌾 */ SheafRice_E0_6,
            /* 🌿 */ Herb_E0_6,
            /* ☘️ */ Shamrock_E1_0,
            /* 🍀 */ FourLeafClover_E0_6,
            /* 🍁 */ MapleLeaf_E0_6,
            /* 🍂 */ FallenLeaf_E0_6,
            /* 🍃 */ LeafFlutteringWind_E0_6,
            /* 🪹 */ EmptyNest_E14_0,
            /* 🪺 */ NestEggs_E14_0,
        };
    }
}
